val default : LTerm_style.color
val blue : LTerm_style.color
val dark_blue : LTerm_style.color
val dark_green : LTerm_style.color
val dark_grey : LTerm_style.color
val dark_red : LTerm_style.color
val light_grey : LTerm_style.color
val light_red : LTerm_style.color
val purple : LTerm_style.color
val yellow : LTerm_style.color
